language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# command to run tests
script:
  - ./test.sh

